[package]
name = "monkey"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sui-sdk = { git = "https://github.com/MystenLabs/sui", branch = "main" }
sui-framework =  { git = "https://github.com/MystenLabs/sui", branch = "main"}
sui-json-rpc = { git = "https://github.com/MystenLabs/sui", branch = "main"}
sui-transaction-builder = { git = "https://github.com/MystenLabs/sui", branch = "main"}
sui-json-rpc-types = { git = "https://github.com/MystenLabs/sui", branch = "main"}
sui-types = { git = "https://github.com/MystenLabs/sui", branch = "main"}
sui-json = { git = "https://github.com/MystenLabs/sui", branch = "main"}
sui-core = { git = "https://github.com/MystenLabs/sui", branch = "main"}
sui-config = { git = "https://github.com/MystenLabs/sui", branch = "main"}
sui-keys = { git = "https://github.com/MystenLabs/sui", branch = "main"}
shared-crypto = { git = "https://github.com/MystenLabs/sui", branch = "main"}
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "84fd7c7428c5f59185aecc56a2e0a006e8e07de1" }

bcs = "0.1.4"

dirs = "5.0.0"
anyhow = "1.0.64"
tokio = { version = "1", features = ["full"] }
futures = "0.3.23"
hex = "0.4.3"