[package]
name = "pyth-receiver-sdk"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]
name = "pyth_receiver_sdk"


[dependencies]
anchor-lang = ">=0.28.0"
pythnet-sdk = { path = "../../../pythnet/pythnet_sdk"}
solana-program = "*"
