[package]
name = "Pyth"
version = "0.0.1"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "3a70c4374090b020b95465787f3220a95d8ab0ba"

[dependencies.Wormhole]
git = "https://github.com/wormhole-foundation/wormhole.git"
subdir = "sui/wormhole"
rev = "sui/mainnet"

[addresses]
pyth = "0x250"
wormhole = "0x200"