name: P2W SDK Rust

on:
  pull_request:
    paths: ["third_party/pyth/p2w-sdk/rust/**"]
  push:
    branches:
      - dev.v2
    paths: ["third_party/pyth/p2w-sdk/rust/**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./third_party/pyth/p2w-sdk/rust/
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
